---
driver:
  name: docker
  socket: <%= ENV['DOCKER_HOST'] %>
  provision_command: curl -L https://www.getchef.com/chef/install.sh | bash

provisioner:
  name: chef_solo
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: debian-7.4
  - name: centos-6.4

suites:
  - name: client
    run_list: ["recipe[mysql-community::client]"]
  - name: server
    run_list: ["recipe[mysql-community::server]"]
    attributes:
      mysql:
        server_root_password: "rootpass"
        server_debian_password: "debpass"
        server_repl_password: "replpass"
