source 'https://rubygems.org'

gem 'berkshelf'
gem 'chef-sugar'
gem 'chefspec'
gem 'foodcritic'
gem 'guard-bundler'
gem 'guard-foodcritic'
gem 'guard-rspec'
gem 'guard-rubocop'
gem 'kitchen-docker'
gem 'strainer'
gem 'test-kitchen'
